/*1*/ CREATE TABLE DEPT (Dept_ID NUMERIC(7) NOT NULL PRIMARY KEY, Dept_Name VARCHAR2(20));
/*2*/   INSERT INTO DEPT VALUES (10, 'Accounts');
        INSERT INTO DEPT VALUES (NULL, 'TT');
        INSERT INTO DEPT VALUES (20, 'TT');
        INSERT INTO DEPT VALUES ('A1', 'Accounts');
        INSERT INTO DEPT VALUES (30, 'Accounts');