/*1*/ CREATE TABLE MY_EMPLOYEE AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES WHERE 1=2;
/*2*/ DESC MY_EMPLOYEE;
/*3*/ INSERT INTO MY_EMPLOYEE VALUES (201, 'Michael', 'Hartstein', 20, 13000);
/*4*/ INSERT INTO MY_EMPLOYEE VALUES (202, 'Pat', 'Fay', 20, NULL);
/*5*/ INSERT INTO MY_EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID) VALUES(203, 'Susan', 'Marvis', 40);
/*6*/ INSERT ALL
        INTO MY_EMPLOYEE VALUES (205, 'Shelley', 'Higgins', 110, 12000)
        INTO MY_EMPLOYEE VALUES (100, 'Steven', 'King', 90, 24000)
        INTO MY_EMPLOYEE VALUES (101, 'Neena', 'Kochhar', 90, 17000)
        INTO MY_EMPLOYEE VALUES (102, 'Lex De', 'Haan', 90, 17000)
        INTO MY_EMPLOYEE VALUES (111, 'Ismael', 'Sciarra', 100, 7700)
        INTO MY_EMPLOYEE VALUES (112, 'Jose Manuel', 'Urman', 100, 7800)
        INTO MY_EMPLOYEE VALUES (204, 'Hermann', 'Baer', 70, 10000)
      SELECT * FROM DUAL;
/*7*/ UPDATE MY_EMPLOYEE SET SALARY = (SALARY * 110 / 100) WHERE DEPARTMENT_ID = 90;
/*8*/ UPDATE MY_EMPLOYEE SET LAST_NAME = 'Higgins' WHERE EMPLOYEE_ID = 202;
/*9*/ DELETE FROM MY_EMPLOYEE WHERE (FIRST_NAME LIKE '%man%') OR (LAST_NAME LIKE '%man%');