/*1*/ DESC DEPARTMENTS;
/*2*/ SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, HIRE_DATE AS STARTDATE FROM EMPLOYEES;
/*3*/ SELECT DISTINCT JOB_ID FROM EMPLOYEES;
/*4*/ SELECT EMPLOYEE_ID AS "Emp #", LAST_NAME AS "Employee", JOB_ID AS "Job", HIRE_DATE AS "Hire Date" FROM EMPLOYEES;
/*5*/ SELECT LAST_NAME ||', '|| JOB_ID "Employee and Title" FROM EMPLOYEES;
